USE shareprice;

CREATE TABLE IF NOT EXISTS customer (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    forename VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    PRIMARY KEY(id),
    UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS shareprice_user (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT(20) UNSIGNED NOT NULL,
    username VARCHAR(100),
    password VARCHAR(128),
    enabled BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
